### ISSUE TITLE
Git tag for version 1.0.3.

### ISSUE THREAD

**Issue by fabionatali** [hlissner/emacs-hide-mode-line#10]
### What would you like to know?

Dear Author, would you please consider creating a Git tag for version 1.0.3? This would make things marginally easier in terms of downstream packaging - at least for my distribution. Thanks, best wishes, Fabio.

**Comment by hlissner** [comment]
Sorry for the tremendously late response, but [it's done](https://github.com/hlissner/emacs-hide-mode-line/releases/tag/v1.0.3). Thanks for letting me know!

**Comment by fabionatali** [comment]
Hi Henrik, thanks, much appreciated! :pray:
