### ISSUE TITLE
How can this be toggled globally?

### ISSUE THREAD

**Issue by WorldsEndless** [hlissner/emacs-hide-mode-line#3]
Is there a simple way to make this a global hiding of the modeline in addition to the current buffer-local version?

**Comment by hlissner** [comment]
How about:

```lisp
(add-hook 'after-change-major-mode-hook #'hide-mode-line-mode)
```

Or simply `(setq-default mode-line-format nil)`?

**Comment by WorldsEndless** [comment]
Thanks, but I can clarify: I don't want the modeline to be gone everywhere -- I want the modeline to be toggle-able (with a keystroke) at a global level, so if I'm in a .org and toggle modeline, then switch to an already open .clj buffer, it respects whatever action my toggle just made.

**Comment by hlissner** [comment]
I just added `global-hide-mode-line-mode` in 7fce443. You can bind that to a key and toggle it as you like.

I'll consider this issue resolved. Thanks for bringing it to my attention!
