### ISSUE TITLE
global-hide-mode-line-mode cannot be disabled if enabled from code

### ISSUE THREAD

**Issue by WorldsEndless** [hlissner/emacs-hide-mode-line#4]
**What Works:** `M-x global-hide-modeline-mode` toggles the presence of modelines globally.

**Almost Works:** Evaluating the code `(global-hide-modeline-mode)` hides the modeline everywhere

**FAILS:** A second evaluation of `(global-hide-modeline-mode)`, with or without args, does nothing. The modeline cannot be recovered easily, and buffer-local hide-modeline also does nothing after this. 

As a result, binding global-hide-modeline-mode to a key seems to fail.

**Comment by WorldsEndless** [comment]
Example code that produces this problem: 

``` elisp
(defun tsa/hide-mode-line (arg)
  "Toggle modeline globally, or just in this window with arg"
  (interactive "p")
  (if (= arg 4)
      (progn
	(message "toggle global modeline from %s" global-hide-mode-line-mode)
	(global-hide-mode-line-mode))
    (progn
      (message "toggle buffer modeline from %s" hide-mode-line-mode)
      (hide-mode-line-mode (if hide-mode-line-mode -1 +1)))
    ))
```

**Comment by vyorkin** [comment]
Can confirm that this is still an issue. For example, the following `t m` keybinding doesn't work:

```elisp
(use-package hide-mode-line
 :config
 (add-hook 'completion-list-mode-hook #'hide-mode-line-mode)
 (nmap
   :prefix my/leader
   "t m" 'global-hide-mode-line-mode))
```

**Comment by hlissner** [comment]
Sorry for the _super_ late response. cc81ba3 should finally fix this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
