### ISSUE TITLE
how to leave one line

### ISSUE THREAD

**Issue by yanglimingcn** [hlissner/emacs-hide-mode-line#6]
Can hide-mode-line leave one line, because when split-window-below, two window can not distinguish.

**Comment by hlissner** [comment]
Use `window-divider-mode` (built into Emacs) to have larger lines in between windows. e.g.

```elisp
(setq window-divider-default-places t
      window-divider-default-bottom-width 4
      window-divider-default-right-width 4)
(window-divider-mode +1)
```

This only works in GUI Emacs, however. In terminal Emacs there is no way to add a bottom border without a modeline.

**Comment by yanglimingcn** [comment]
thank a lot
